version: '3.4'

services:
  kiwi.api:
    image: ${DOCKER_REGISTRY-}kiwiapi
    build:
      context: .
      dockerfile: Kiwi.API/Dockerfile
    networks:
      - KiwiNet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    ports:
     - "9200:9200"
    volumes:
     - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
     - KiwiNet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    ports:
     - "5601:5601"
    depends_on:
     - elasticsearch
    networks:
     - KiwiNet
  
networks:
  KiwiNet:
    driver: bridge

volumes:
  elasticsearch-data: